import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Acer Aspire 5 Gaming Laptop',
      slug: 'Acer Aspire 5 Gaming Laptop',
      category: 'Laptop',
      image: 'https://m.media-amazon.com/images/I/41dgHDQs4RL._SX300_SY300_QL70_FMwebp_.jpg', // 679px × 829px
      price: 1200,
      countInStock: 10,
      brand: 'Acer',
      rating: 4.5,
      numReviews: 10,
      description: 'Acer Aspire 5 Gaming laptop is powered by the latest 12th Gen Intel Core i5 processor consisting of 12 cores for multitasking and productivity',
    },
    {
      // _id: '2',
      name: 'Acer Extensa 15 Laptop',
      slug: 'Acer Extensa 15 Laptop',
      category: 'Laptop',
      image: 'https://m.media-amazon.com/images/I/41KEAvh1cnL._SX300_SY300_QL70_FMwebp_.jpg',
      price: 2500,
      countInStock: 0,
      brand: 'Acer',
      rating: 4.0,
      numReviews: 10,
      description: 'Fast & easy computing Perfect budget laptop for students and working professionals that helps get jobs done quickly and efficiently thanks to the Intel Core i5-1135G7 processor.',
    },
    {
      // _id: '3',
      name: 'Honor MagicBook 14',
      slug: 'Honor MagicBook 14',
      category: 'Laptop',
      image: 'https://m.media-amazon.com/images/I/31bgVrI5qoL._SX300_SY300_QL70_FMwebp_.jpg',
      price: 950,
      countInStock: 15,
      brand: 'Honour',
      rating: 4.5,
      numReviews: 14,
      description: 'Operating System & Preinstalled Software: Windows 11 Home 64 Plus Single Language | Microsoft Office Home & Student 2021| McAfee LiveSafe (30 days free trial as default) |Pre-installed Alexa built-in- Your life simplified with Alexa. Just ask Alexa to check your calendar, create to-do lists, shopping lists, play music, set reminders, get latest news and control smart home.',
    },
    {
      // _id: '4',
      name: 'HP 15s,11th Gen Intel Core i3',
      slug: 'HP 15s,11th Gen Intel Core i3',
      category: 'Laptop',
      image: 'https://m.media-amazon.com/images/I/51CHnrWocRL._SX300_SY300_QL70_FMwebp_.jpg',
      price: 65,
      countInStock: 5,
      brand: 'HP',
      rating: 4.5,
      numReviews: 10,
      description: 'Processor: Intel Core i3-1115G4 (up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe M.2 SSD',
    },
    {
      name: 'Redmi 12C(Royal Blue)',
      slug: 'Redmi 12C(Royal Blue)',
      category: 'Mobile',
      image: 'https://m.media-amazon.com/images/I/81itQPVn-GL._SX425_.jpg',
      price: 650,
      countInStock: 5,
      brand: 'Redmi',
      rating: 4.5,
      numReviews: 10,
      description: 'Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x',
    },
    {
      name: 'OnePlus Nord CE 2 Lite 5G ',
      slug: 'OnePlus Nord CE 2 Lite 5G',
      category: 'Mobile',
      image: 'https://m.media-amazon.com/images/I/41mDAtPMDKL._SX300_SY300_QL70_FMwebp_.jpg',
      price: 750,
      countInStock: 5,
      brand: 'oneplus',
      rating: 4.5,
      numReviews: 10,
      description: 'Camera Features: AI scene enhancement, Dual-View Video, HDR, Night Portrait, Panorama Mode, Retouch Filters, 1080p video at 30 fps, SLO-MO: 720p video at 120 fps, TIME-LAPSE: 1080p video at 30 fps, Video editor, Face unlock, Screen flash, HDR, NIGHT, PORTRAIT, TIME-LAPSE, Retouch, Filters',
    },
    {
      name: 'boAt Rockerz 558',
      slug: 'boAt Rockerz 558',
      category: 'Headphone',
      image: 'https://m.media-amazon.com/images/I/61JKDwA+ntL._SY355_.jpg',
      price: 150,
      countInStock: 5,
      brand: 'boat',
      rating: 4.5,
      numReviews: 10,
      description: 'boAt Rockerz 558 Bluetooth Wireless Over Ear Headphones with Mic Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation(Army Green)',
    },
    {
      name: 'JBL C100S Headphone',
      slug: 'JBL C100S Headphone',
      category: 'Headphone',
      image: 'https://m.media-amazon.com/images/I/51Q8DUDT2eL._SY355_.jpg',
      price: 90,
      countInStock: 5,
      brand: 'boat',
      rating: 4.5,
      numReviews: 10,
      description: 'JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Angled Buds for Comfort fit (Black)',
    }
  ],
};
export default data;
